#!/usr/bin/env bash
# Installs and configures Nginx on a new Ubuntu machine.

apt-get update -y
apt-get install nginx -y

echo "Hello World!" | tee /var/www/html/* > /dev/null 2>&1

ufw allow 'Nginx HTTP'

service nginx restart
