#!/usr/bin/env bash
# Installs and configures Nginx on a new Ubuntu machine.
# Configures redirect_me page to redirect to https://www.google.com

# update machine and install nginx
apt-get update -y
apt-get install nginx -y

# update default html file that comes with nginx
echo "Hello World!" | tee /var/www/html/* > /dev/null 2>&1

# configure the server block
echo  "server {
      listen 80 default_server;
      listen [::]:80 default_server;

      root /var/www/html;
      index index.html index.htm;

      location /redirect_me {
      	       return 301 https://www.google.com;
      }
}" > /etc/nginx/sites-available/default

# restart nginx
service nginx restart
