#!/usr/bin/env bash
# Installs and configures Nginx on a new Ubuntu machine.
# Configures invalid pages to redirect to https://www.google.com

# update machine and install nginx
apt-get update -y
apt-get install nginx -y

# update default html file that comes with nginx
echo "Hello World!" | tee /var/www/html/* > /dev/null 2>&1
# set nginx to listen on port 80
ufw allow 'Nginx HTTP'

# replace the default 404 status code for error_page with 301
sed -i 's/=404;/=301 https:\/\/www.google.com;/g' /etc/nginx/sites-available/default

# restart nginx
service nginx restart
