#!/usr/bin/env bash
# Manages the script "manage_my_process".
# This script takes one argument.
#   * When the argument is `start`:
#      1. Executes the manage_my_process script
#      2. Creates a file containing its own PID in /var/run/my_process.pid
#      3. Displays "manage_my_process started"
#   * When the argument is `stop`:
#      1. Stops manage_my_process
#      2. Deletes the file /var/run/my_process.pid
#      3. Displays "manage_my_process stopped"
#   * When the argument is `restart`:
#      1. Stops manage_my_process
#      2. Deletes the file /var/run/my_process.pid
#      3. Executes the manage_my_process script
#      4. Creates a file containing its own PID in /var/run/my_process.pid
#      5. Displays "manage_my_process started"
#   * If the command is none of these three(3):
#      1. Display "Usage: manage_my_process {start|stop|restart}"


case $1 in
    start)
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
	;;
    stop)
	pkill -f /manage_my_process
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
    restart)
	pkill -f /manage_my_process
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
