#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, specifically:
# The username field
# The user ID field
# The home directory path field

while read -r line
      do
	echo "$line" | cut -d ':' -f1,3,6
done < /etc/passwd