#!/usr/bin/env bash
# This script loops 10 times and displays "bad luck" on the 4th iteration, \
displays "good luck" on the 8th iteration and "Best School" for other iterations
i=1
while [ $i -lt 11 ]
      do
	if [ $i = 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
