#!/usr/bin/env bash
# This script gives information about the 'School' file.

# checks if the file school exists
if [ ! -e school ]
   then
       echo "school file does not exist"
else
    echo "school file exists"
    # checks if it is empty
    if [ ! -s school ]
        then
	    echo "school file is empty"
    else
	echo "school file is not empty"
    fi
    # checks if it is a regular file
    if [ -f school ]
        then
	    echo "school is a regular file"
    fi
fi
