#!/usr/bin/env bash
# Run nginx as user `nginx` on port 8080.
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's.listen 80.listen 8080.g' /etc/nginx/sites-available/default
sed -i 's.listen \[::\]:80.listen \[::\]:8080.g' /etc/nginx/sites-available/default
kill "$(pgrep apache2 | head -1)"
su nginx -c "service nginx start"
